# Generated by Django 2.1.1 on 2018-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=120, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('login_error_num', models.IntegerField(default=0, verbose_name='登录错误次数')),
                ('create_date', models.DateField(verbose_name='记录创建时间')),
                ('last_login_date', models.DateField(verbose_name='最后一次登录时间')),
            ],
        ),
    ]
