# Generated by Django 2.1.1 on 2018-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=120, verbose_name='角色名')),
                ('description', models.CharField(max_length=120, verbose_name='描述')),
            ],
            options={
                'db_table': 'f_role',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='f_user',
        ),
    ]
